nameOverride: neededornot

deploymentAnnotations: {}
imagePullSecret: 
containerImage: 
  image: some/image
  tag: latest
  imagePullPolicy: IfNotPresent
  
persistence:
  dataDir:
    enabled: true
    Size: 1Gi
#    existingClaim: 
    mountPath: /data

spec:
  strategy: 
    type: Recreate

podAnnotations: {}

resources:
  requests:
    memory: 512Mi
    cpu: 500m

probes:
  readinessProbe:
    enabled: false
  livenessProbe:
    enabled: false
  startupProbe:
    enabled: false

container:
  port: 7878
  protocol: TCP

# extraVolumes:
#   - volumeMounts:
#       - name: nfs
#         mountPath: /mnt/volume
#         readOnly: true
#     volumes:
#       - name: nfs
#         server: some.nfs.server.com
#         path: /
#         mountOptions:
#           - port=2049
#           - hard
#           - vers=4
extraVolumes: []

# Service
service:
  serviceAnnotations: {}
  # ClusterIP, NodePort
  serviceType: ClusterIP
  nodePort: 30000
  #externalTrafficPolicy: Cluster
  #internalTrafficPolicy: Cluster
    
ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: radarr.domain.xyz
      paths:
        - path: /
          pathType: Prefix

  tls:
    - hosts:
        - radarr.domain.xyz
      secretName: certificate-production
