apiVersion: v1
kind: Service
metadata:
  name: {{ template "application.fullname" . }}
  labels:
    app: {{ template "application.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    {{ toYaml .Values.service.serviceAnnotations | indent 4 }}
spec:
  type: {{ .Values.service.serviceType }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.service.internalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.internalTrafficPolicy }}
  {{- end }}
  ports:
  - name: {{ template "application.fullname" . }}
    port: {{ .Values.container.port }}
    targetPort: {{ template "application.fullname" . }}
    {{- if ( eq .Values.service.serviceType "NodePort" ) }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
    protocol: {{ .Values.container.protocol }}
{{- range .Values.extraPorts }}
{{ toYaml . | indent 2 }}
{{- end }}
  selector:
    app: {{ template "application.fullname" . }}
